### ISSUE TITLE
publishing gh-pages from travis fails

### ISSUE THREAD

**Issue by vobujs** [UI5Lab/UI5Lab-central#13]
just occured when merging https://github.com/UI5Lab/UI5Lab-central/pull/12 - ui5lab.io now throws a 404

**Comment by Michadelic** [comment]
there is a field in the UI5Lab-central settings page that is currently reset to blank when a new build is triggered. This field is it:
https://help.github.com/articles/adding-or-removing-a-custom-domain-for-your-github-pages-site/

I did not found a solution yet to keep this field when deploying, so i manually set it to "ui5lab.io" again.
Works for now with this manual workaround but keeping the ticket open to find an automated solution

**Comment by Michadelic** [comment]
Fixed by adding a CNAME file to the preview folder that is automatically deployed to the gh-pages root

**Comment by Michadelic** [comment]
https://github.com/UI5Lab/UI5Lab-central/blob/gh-pages/CNAME
