### ISSUE TITLE
Landing page is not optimized for phone

### ISSUE THREAD

**Issue by Michadelic** [UI5Lab/UI5Lab-central#15]
The colored bubbles are squeezed into the description text on phones.
To address this issue the bubbles should be displayed below the explanation texts on phone and small screen resolutions

Steps to reproduce:
1. open http://ui5lab.io/
2. reduce the screen width to less than 500px or open it on a phone in Portrait mode
3. notice that the text in brackets and the bubbles overlap

**Comment by AnnFr** [comment]
Hello Michadelic, I observed the issue only on the desktop screen emulation in die Developer Tools. When I displayed the page with 2 different proper cell phones together with a colleague, we could not reproduce the issue anymore (iPhone and Samsung).
