### ISSUE TITLE
Link "How to use this library" does not work

### ISSUE THREAD

**Issue by htammen** [UI5Lab/UI5Lab-central#45]
When I click at the link "How to use this library" I always get redirected to https://github.com/UI5Lab/UI5Lab-central/blob/master/docs/ConsumeLibrary.md
Should this link go to this file instead?
https://github.com/UI5Lab/UI5Lab-central/blob/master/docs/how_to/consume_library.md

**Comment by Michadelic** [comment]
Done, we haven't updated the documentation links after switching to docsify
Thanks for the feedback!
